### PR TITLE
Iss12 create release

### LINKED ISSUE #12: implement action to compile tex files and create release

### PR DESCRIPTION
**Pull request by BWhannou**
closes #12 
tutorial:
https://github.com/marketplace/actions/github-action-for-latex
https://github.com/softprops/action-gh-release

### CODE REVIEW

**Comment by BWhannou** [comment]
@akouete-kpakpo ready for review

**Comment by akouete-kpakpo** [comment]
@BWhannou this is awesome!!!

can't wait to see the result

**Review by akouete-kpakpo — APPROVED** [review]
approved

should we also remove the pdf file for the presentation?

**Comment by BWhannou** [comment]
@akouete-kpakpo yes I removed the pdf. Now, I need to test some command lines to convert the notebooks in pdf

**Pull request merged**
